### ISSUE TITLE
I'm using docbox! But i want to make it dynamic

### ISSUE THREAD

**Issue by stepanushariara** [tmcw/docbox#130]
Hi Team,

I want to make documentation only viewing the json.
But the challenge is that json comes dynamically by requesting our API gateway.
In my mind i just thinking create API request and get json response and put it into md file.
But i cannot do that because i am newbie.
ANyone can help me ?

**Comment by tmcw** [comment]
This might be a bit of a tall task if you haven't made API requests from JavaScript or worked on a React project. The starting point would be [the section component](https://github.com/tmcw/docbox/blob/master/src/components/section.js), assuming that you want to request from your API dynamically on the web – and in that case, it won't be putting the code _in_ the markdown file, because by the time docbox is deployed, the markdown file is compiled into the JavaScript application.
