### ISSUE TITLE
Implementing React's Routing

### ISSUE THREAD

**Issue by gogears** [tmcw/docbox#134]
**1st approach:**
1. May i know how to implement react's routing process within the docbox application
2. How to make multiple routing to work with docbox application

**2nd approach:**
1. How to import Docbox as npm modules within the existing react application

**Comment by tmcw** [comment]
React doesn't have one official router. Some applications use [react-router](https://reacttraining.com/react-router/), but there are many other options, like reach router.

Docbox doesn't use a routing system, because it's simple enough that it doesn't need one. Sorry, refactoring it to use a router is too complicated and opinionated a task to answer in an issue.

For the second approach: I wouldn't recommend using docbox as an npm module. It's made to be cloned as a git repository. You can copy the files into another project if you want to make it part of another application.

**Comment by gogears** [comment]
Hi tmcw,

Thank for replying me back immediately for my support. Can you be able to suggest me some **api documentation** module/component which can be integrated with **[ReactJS](https://reactjs.org/) or [AngularJS](https://angularjs.org/)** application, were we try to implement them in routing process.

**Reference Link:** https://stackoverflow.com/questions/58851909/suggest-me-api-documentation-tool
