### ISSUE TITLE
How do write multiple api version?

### ISSUE THREAD

**Issue by morenice** [tmcw/docbox#138]
Thanks for sharing good tools.

We used docbox for api document server.
But, I don't know how do write content.js for multiple api version.

Could you explain to write multiple api version page?

**Comment by tmcw** [comment]
It's really up to you: ideally, APIs have only one documented version at a time and the old documentation is very hard to find. Otherwise (speaking from experience), people will happen upon the old documentation via Google, try to use it with the new version, and fail.

So, you can have multiple docbox instances per version, or you can offer old versions as rendered Markdown on GitHub, or you can document multiple versioned endpoints in the same documentation - it's up to you.
