### ISSUE TITLE
how to use .env file in project

### ISSUE THREAD

**Issue by magal-ti** [tmcw/docbox#140]
Hello guys

Probably is a beginer error, but I need help.

I trying to use a .env file to configure my enviroment, because I need to change the link in determinate enviroment, but don't work.
I tryed only include the file and don't work, (because I read, In React is default configured)
I tryed install the lib dotenv, I configured like the example in the lib and don`t work.
every return is undefined when I show the variable:

`console.log(process.env.REACT_APP_TEST)`

I tryed to use the prefix REACT_APP
When I show the `console.log(process.env)` this return one empty object and if I include the file .env don`t reading my variable in the file.

Can you help me the best way to use .env file in that project?

**Comment by tmcw** [comment]
Hi Vinicius -

Docbox is an application that runs in the browser, with browserify. process.env is something from Node.js, and by default [browserify](http://browserify.org/), which translates code that runs in Node into code that runs in a browser, does not support process.env.

I'd recommend using [envify](https://github.com/hughsk/envify), which will replace something like

```js
console.log(process.env.REACT_APP_TEST)
```

with the code for what that value is, like

```js
console.log("foo")
```

But additionally, you'll need to use a different approach than `dotenv`, because dotenv works on the wrong level of abstraction for this kind of problem. So you can define the env variables inline, like changing the [build script in package.json](https://github.com/tmcw/docbox/blob/master/package.json#L14) to include another env variable next to NODE_ENV, or swapping the cross-env call with an [env-cmd](https://github.com/toddbluhm/env-cmd) call.

**Comment by magal-ti** [comment]
Thanks @tmcw 

You save my life
