### ISSUE TITLE
Auto generate snippets

### ISSUE THREAD

**Issue by Kikobeats** [tmcw/docbox#46]
Could be awesome use https://apiembed.com/ for auto generate specific language snippets

**Comment by tmcw** [comment]
Looks like [httpsnippet](https://github.com/Mashape/httpsnippet) is the open source part we'd use in that case.

This idea is a bit different than the vision for docbox. For my original use case, for instance - [Mapbox's api documentation](https://www.mapbox.com/api-documentation/), the theory is that you use an SDK for accessing the API, and often the examples will offer variations of a given endpoint that has different parameters.

Auto-generating API calls is cool, but it trades a lot of expressiveness - ability to use SDKs, show different examples, add comments - for not that much typing-savings. Auto-generating API call code doesn't really allow the human editor to add their knowledge to documentation, which is the main intent of documentation - otherwise I'd write a fancy WSDL formatter.

That said, this is about the usecases I've seen and the priorities I have: those may not be everyone's. So, closing this one as the 'keeper of the vision' for this project but I heartily encourage others to fork or create similar projects if they believe that auto-generation is a win.
