### ISSUE TITLE
Multiple headings with the same subtitle

### ISSUE THREAD

**Issue by ghost1face** [tmcw/docbox#51]
I'm creating documentation that looks similar to:

### POST

When I click on the Get url under Resource 2, both `GET` urls are underlined.  I started to dig through this to address but looks like it will be a little larger.  Is this something you know about and are addressing? Or are you not so open to adjusting for these changes?

**Comment by tmcw** [comment]
I've been avoiding this form in most of the docbox usecases: Though, for instance, I could get `remark` to set the slug for the second `GET` to `get-2`, That means that every time you add a new resource, that 'permalink' will point to a different GET header.

There's [a test that enforces this standard](https://github.com/tmcw/docbox/blob/7a7a39df3975b92a8cb9a374ee0880997490a706/test/content.js#L36-L55) and will fail on your input. If you look at [Mapbox's documentation](https://www.mapbox.com/api-documentation/#retrieve-an-html-slippy-map), you'll see how this works in production - that the GET/POST HTTP method is part of the technical documentation, rather than a header, and headers are unique and describe _what_ the method does, not _how_ to make it.

**Comment by ghost1face** [comment]
Understood, I originally went the *behavioral* route but tried using HTTP method to simplify the navigation.  I started to implement a slug that would resemble the hierarchy ie  `resource1-get` but this would make linking internally to other sections very fragile.  I was more curious.  

Thanks for the documentation and your feedback!  Will mark as closed.
