### ISSUE TITLE
Support for API Versions

### ISSUE THREAD

**Issue by akshayrawat** [tmcw/docbox#54]
Are there any plans to support API versions?

**Comment by tmcw** [comment]
I don't have substantive work plans for this repository: I happily review & usually accept pull requests for fixes & features that fit the intended scope, but don't actively write new code here because, well, the project does what it set out to do.

The approach we took for Mapbox was that REST API documentation, published with docbox, is for a single version: the active version. Changes to that documentation are published [as a page](https://www.mapbox.com/api-documentation/changelog.html), which is just a usual page. No fancy system for that. And documentation for old versions is just formatted Markdown, without a docbox site.

I'd be interested in approaches here, but cautious about doing too much more to promote other versions. What I've seen is that documenting older versions of APIs can be a trap: unless you make sure that there are bright red warning signs everywhere saying that "this is the old stuff, don't use it for new development", people will use it for new development. Even if you add bright red warning signs everywhere, people will often ignore them and still use old APIs for who knows why :)

Have you seen approaches that work well for this? Or have a usecase in mind?

**Comment by tmcw** [comment]
Closing - happy to continue the conversation, but not seeing an action here.
